### ISSUE TITLE
テレポートが二回発動するので使いづらい

### ISSUE THREAD

**Issue by Anpan715** [Chuzume/Chuzume-s-Toolbox#4]
スニーク時の使用で反対側まで抜けてしまうことが多いです。
仕様上仕方ないとは思うんですがどうにかなりませんか？

**Comment by Chuzume** [comment]
スニーク時の使用は反対側まで抜けるものです…

**Comment by Anpan715** [comment]
言い方が悪かったですね、すみません
単押しだと二回発動してしまって、入りたい空間のさらに先にテレポートしてしまうという意味です

**Comment by Anpan715** [comment]
言い方が悪かったですね、すみません
単押しで発動すると２度テレポートしてしまって、入りたい空間のさらに先まで抜けてしまうという意味です

**Comment by Anpan715** [comment]
間違えて閉じてしまいました、すみません

**Comment by Chuzume** [comment]
クリック時には4tickのクールダウンが発生して、その間はクリックを受け付けないほか、2度テレポートしたとしても先まで抜けないので、ちょっと分からないですね

**Comment by Anpan715** [comment]
こんな感じですね
おそらく短いクリックのときに二回抜けてしまうみたいです。
https://github.com/user-attachments/assets/0f880e1b-96ee-4d3a-8879-840b3bbd32ef

**Comment by Chuzume** [comment]
お待たせしました、修正したバージョンをリリースしました。
